#!/bin/bash

GENERATOR=../finite
DIM_X=16
DIM_Y=16
DIM_Z=16
STEN_ORDER=4
ITERATION=1
PIMS=0
CAPACITY=8
BSIZE=256
VAULTS=32
CACHESIZE=8192

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
 -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHESIZE"

 $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
  -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHESIZE
