#!/bin/bash

GENERATOR=../finite
DIM_X=65
DIM_Y=65
DIM_Z=65
STEN_ORDER=10
ITERATION=1
PIMS=0
CAPACITY=8
BSIZE=256
VAULTS=32
CACHESIZE=4

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
 -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHESIZE"

 $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
  -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHESIZE
