#!/bin/bash

GENERATOR=../grid_generator
DIM_X=128
DIM_Y=128
DIM_Z=128
GRID_TYPE=double
# GRID_TYPE=Integer
STEN_TYPE=2
STEN_ORDER=1
CAPACITY=8
BSIZE=256

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -t $GRID_TYPE\
 -T $STEN_TYPE -O $STEN_ORDER -c $CAPACITY -b $BSIZE"

$GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -t $GRID_TYPE -T $STEN_TYPE\
 -O $STEN_ORDER -c $CAPACITY -b $BSIZE
