#!/bin/bash

GENERATOR=../grid_generator
DIM_X=256
DIM_Y=256
DIM_Z=256
GRID_TYPE=double
# GRID_TYPE=Integer
STEN_TYPE=2
STEN_ORDER=1
STEN_COEFF=4
PIMS=0
CAPACITY=8
BSIZE=256
VAULTS=32

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z\
-t $GRID_TYPE -T $STEN_TYPE -O $STEN_ORDER -C $STEN_COEFF\
-p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS"

$GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -t $GRID_TYPE -T $STEN_TYPE\
 -O $STEN_ORDER -C $STEN_COEFF -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS
