#!/bin/bash

GENERATOR=../stencil
DIM_X=1024
DIM_Y=1024
DIM_Z=0
GRID_TYPE=double
# GRID_TYPE=Integer
STEN_TYPE=0
STEN_ORDER=5
STEN_COEFF=1
ITERATION=5
PIMS=0
CAPACITY=8
BSIZE=256
VAULTS=32
CACHESIZE=8192

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z\
-t $GRID_TYPE -T $STEN_TYPE -O $STEN_ORDER -C $STEN_COEFF\
-i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHESIZE"

$GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -t $GRID_TYPE -T $STEN_TYPE\
 -O $STEN_ORDER -C $STEN_COEFF -i $ITERATION -p $PIMS -c $CAPACITY\
 -b $BSIZE -v $VAULTS -a $CACHESIZE
