#!/bin/bash

GENERATOR=../stsim_cache
DIM_X=64
DIM_Y=64
DIM_Z=64
STEN_ORDER=8
ITERATION=10
PIMS=0
CAPACITY=8
BSIZE=256
VAULTS=32
CACHE=8192

echo "Executing: $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
 -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHE"

 $GENERATOR -x $DIM_X -y $DIM_Y -z $DIM_Z -o $STEN_ORDER\
  -i $ITERATION -p $PIMS -c $CAPACITY -b $BSIZE -v $VAULTS -a $CACHE
