#!/bin/bash

STENCIL=../stencil_memory


BSIZE=256
BUSIZE=512
CAPACITY=4
NUMDIVS=1
NUMVAULTS=32
STENTYPE=1
SIZEX=40
SIZEY=0
SIZEZ=0
FILENAME=trace-1.out

echo "Executing: $STENCIL -b $BSIZE -c $CAPACITY -d $NUMDIVS -f $BUSIZE -t $STENTYPE\
 -v $NUMVAULTS -x $SIZEX -y $SIZEY -z $SIZEZ -F $FILENAME"

$STENCIL -b $BSIZE -c $CAPACITY -d $NUMDIVS -f $BUSIZE -t $STENTYPE -v $NUMVAULTS\
 -x $SIZEX -y $SIZEY -z $SIZEZ -F $FILENAME
