#!/bin/bash

STENCIL=../stencil_memory


BSIZE=256
BUSIZE=512
CAPACITY=4
NUMDIVS=1
NUMVAULTS=32
STENTYPE=6
SIZEX=5
SIZEY=5
SIZEZ=5
FILENAME=trace-6.out

echo "Executing: $STENCIL -b $BSIZE -c $CAPACITY -d $NUMDIVS -f $BUSIZE -t $STENTYPE\
 -v $NUMVAULTS -x $SIZEX -y $SIZEY -z $SIZEZ -F $FILENAME"

$STENCIL -b $BSIZE -c $CAPACITY -d $NUMDIVS -f $BUSIZE -t $STENTYPE -v $NUMVAULTS\
 -x $SIZEX -y $SIZEY -z $SIZEZ -F $FILENAME
